/*
 * This file is generated by jOOQ.
 */
package dev.voidframework.persistence.jooq.model.tables.records;


import dev.voidframework.persistence.jooq.model.tables.UnitTestManagedEntity;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UnitTestManagedEntityRecord extends UpdatableRecordImpl<UnitTestManagedEntityRecord> implements Record1<String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.UNIT_TEST_MANAGED_ENTITY.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.UNIT_TEST_MANAGED_ENTITY.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return UnitTestManagedEntity.UNIT_TEST_MANAGED_ENTITY.ID;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public UnitTestManagedEntityRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public UnitTestManagedEntityRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UnitTestManagedEntityRecord
     */
    public UnitTestManagedEntityRecord() {
        super(UnitTestManagedEntity.UNIT_TEST_MANAGED_ENTITY);
    }

    /**
     * Create a detached, initialised UnitTestManagedEntityRecord
     */
    public UnitTestManagedEntityRecord(String id) {
        super(UnitTestManagedEntity.UNIT_TEST_MANAGED_ENTITY);

        setId(id);
    }
}
