/*
 * This file is generated by jOOQ.
 */
package dev.voidframework.persistence.jooq.model;


import dev.voidframework.persistence.jooq.model.tables.UnitTestManagedEntity;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.UNIT_TEST_MANAGED_ENTITY</code>.
     */
    public final UnitTestManagedEntity UNIT_TEST_MANAGED_ENTITY = UnitTestManagedEntity.UNIT_TEST_MANAGED_ENTITY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            UnitTestManagedEntity.UNIT_TEST_MANAGED_ENTITY
        );
    }
}
