/*
 * This file is generated by jOOQ.
 */
package dev.voidframework.persistence.jooq.model;


import dev.voidframework.persistence.jooq.model.tables.UnitTestManagedEntity;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.UNIT_TEST_MANAGED_ENTITY</code>.
     */
    public static final UnitTestManagedEntity UNIT_TEST_MANAGED_ENTITY = UnitTestManagedEntity.UNIT_TEST_MANAGED_ENTITY;
}
