/*
 * This file is generated by jOOQ.
 */
package dev.voidframework.persistence.jooq.model.tables;


import dev.voidframework.persistence.jooq.model.Keys;
import dev.voidframework.persistence.jooq.model.Public;
import dev.voidframework.persistence.jooq.model.tables.records.UnitTestManagedEntityRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function1;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UnitTestManagedEntity extends TableImpl<UnitTestManagedEntityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.UNIT_TEST_MANAGED_ENTITY</code>
     */
    public static final UnitTestManagedEntity UNIT_TEST_MANAGED_ENTITY = new UnitTestManagedEntity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UnitTestManagedEntityRecord> getRecordType() {
        return UnitTestManagedEntityRecord.class;
    }

    /**
     * The column <code>PUBLIC.UNIT_TEST_MANAGED_ENTITY.ID</code>.
     */
    public final TableField<UnitTestManagedEntityRecord, String> ID = createField(DSL.name("ID"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private UnitTestManagedEntity(Name alias, Table<UnitTestManagedEntityRecord> aliased) {
        this(alias, aliased, null);
    }

    private UnitTestManagedEntity(Name alias, Table<UnitTestManagedEntityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>PUBLIC.UNIT_TEST_MANAGED_ENTITY</code> table
     * reference
     */
    public UnitTestManagedEntity(String alias) {
        this(DSL.name(alias), UNIT_TEST_MANAGED_ENTITY);
    }

    /**
     * Create an aliased <code>PUBLIC.UNIT_TEST_MANAGED_ENTITY</code> table
     * reference
     */
    public UnitTestManagedEntity(Name alias) {
        this(alias, UNIT_TEST_MANAGED_ENTITY);
    }

    /**
     * Create a <code>PUBLIC.UNIT_TEST_MANAGED_ENTITY</code> table reference
     */
    public UnitTestManagedEntity() {
        this(DSL.name("UNIT_TEST_MANAGED_ENTITY"), null);
    }

    public <O extends Record> UnitTestManagedEntity(Table<O> child, ForeignKey<O, UnitTestManagedEntityRecord> key) {
        super(child, key, UNIT_TEST_MANAGED_ENTITY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<UnitTestManagedEntityRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_C;
    }

    @Override
    public UnitTestManagedEntity as(String alias) {
        return new UnitTestManagedEntity(DSL.name(alias), this);
    }

    @Override
    public UnitTestManagedEntity as(Name alias) {
        return new UnitTestManagedEntity(alias, this);
    }

    @Override
    public UnitTestManagedEntity as(Table<?> alias) {
        return new UnitTestManagedEntity(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UnitTestManagedEntity rename(String name) {
        return new UnitTestManagedEntity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UnitTestManagedEntity rename(Name name) {
        return new UnitTestManagedEntity(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UnitTestManagedEntity rename(Table<?> name) {
        return new UnitTestManagedEntity(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function1<? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function1<? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
